use_frameworks!

target 'FitScreenKit_Example' do
  pod 'FitScreenKit', :path => '../'

  target 'FitScreenKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Quick'
  end
end
