language: objective-c
os: osx
osx_image: xcode10.3
env:
  matrix:
    # - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
install:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    gem install xcpretty -N --no-ri --no-rdoc
    gem update cocoapods
  elif [ "$TEST_TYPE" = Carthage ]; then    
    brew install carthage || brew upgrade carthage
  fi
script:
- |
  if [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint CRToast.podspec --allow-warnings
    pod lib lint --use-libraries CRToast.podspec --allow-warnings
  elif [ "$TEST_TYPE" = Carthage ]; then
    carthage build --no-skip-current
  fi
# after_success:
# - |
#   if [ "$TEST_TYPE" = "iOS" ]; then
#     bash <(curl -s https://codecov.io/bash)
#   fi

